### ISSUE TITLE
rbd block mount

### ISSUE THREAD

**Issue by todaygood** [todaygood/kubevirt1#2]
https://github.com/kubevirt/kubevirt/issues/4658

```
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: halting-earthquake
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 465Gi
        storageClassName: block-nvme-ewr1
        volumeMode: Block
      source:
        http:
          url: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img
```
